// Weather
import { getFormattedWeather } from '../../services/utility';

export default async function Weather(c: HTMLElement): Promise<void> {
  c.innerHTML = `<div class="page animate-fade-in"><header class="page-header"><h1 class="page-title">Weather</h1><p class="page-subtitle">Current conditions and forecast</p></header><div id="weather-content" class="glass-panel weather-content">Loading weather data...</div></div><style>.weather-content{padding:var(--space-8)}.weather-main{display:flex;align-items:center;gap:var(--space-6);margin-bottom:var(--space-8)}.weather-icon{font-size:var(--text-6xl)}.weather-temp{font-size:var(--text-6xl);font-weight:700;background:var(--gradient-primary);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}.weather-desc{font-size:var(--text-xl);color:var(--text-secondary)}.weather-details{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:var(--space-4);margin-bottom:var(--space-8)}.detail-item{padding:var(--space-4);background:var(--glass-bg);border-radius:var(--radius-lg);text-align:center}.detail-value{font-size:var(--text-2xl);font-weight:600}.detail-label{font-size:var(--text-sm);color:var(--text-secondary)}.forecast-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:var(--space-4)}.forecast-day{text-align:center;padding:var(--space-4);background:var(--glass-bg);border-radius:var(--radius-lg)}.forecast-day-name{font-size:var(--text-sm);color:var(--text-tertiary);margin-bottom:var(--space-2)}.forecast-icon{font-size:var(--text-2xl);margin-bottom:var(--space-2)}.forecast-temps{font-size:var(--text-sm)}</style>`;
  try {
    const weather = await getFormattedWeather();
    const content = document.getElementById('weather-content')!;
    content.innerHTML = `<div class="weather-main"><span class="weather-icon">${weather.icon}</span><div><span class="weather-temp">${weather.temperature}°C</span><p class="weather-desc">${weather.description} in ${weather.location}</p></div></div><div class="weather-details"><div class="detail-item"><span class="detail-value">${weather.feelsLike}°</span><span class="detail-label">Feels Like</span></div><div class="detail-item"><span class="detail-value">${weather.humidity}%</span><span class="detail-label">Humidity</span></div><div class="detail-item"><span class="detail-value">${weather.windSpeed} km/h</span><span class="detail-label">Wind</span></div></div><h3 style="margin-bottom:var(--space-4)">5-Day Forecast</h3><div class="forecast-grid">${weather.forecast.map(d => `<div class="forecast-day"><div class="forecast-day-name">${d.date}</div><div class="forecast-icon">${d.icon}</div><div class="forecast-temps">${d.high}° / ${d.low}°</div></div>`).join('')}</div>`;
  } catch { document.getElementById('weather-content')!.innerHTML = '<p class="muted" style="padding:var(--space-6)">Failed to load weather data</p>'; }
}
